name: linter-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter check
        run: make lint
